//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode23Day25.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode23Day25.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to llq: tzg
        ///dns: dkp
        ///fzx: hsc
        ///qvt: dqr mzz spl
        ///gvq: nql mmh ngb
        ///nvc: gkt rhz
        ///dvq: zqg lpt fdm btx
        ///ghj: nnd
        ///znm: ggz fqd ptj ztp
        ///llg: pqx vbf szn zcr
        ///nsm: cch fgv
        ///fbq: dbv tts ltb
        ///kbc: nhr jjj
        ///vdf: vct
        ///fcq: fnv tgd ltb hjv drn mss phg
        ///fqj: gjh
        ///xhj: rqs zhk
        ///qkb: xbd hlx svj rph cbx
        ///kgr: htp rfz
        ///rhj: vdt pxz hzj rqs mll
        ///cgb: rdj tkc smj hgh
        ///vvf: dlj
        ///gxg: vdh hlf hlg
        ///cnz: vtf xnp ltl
        ///hsc: jnd
        ///lcf: xtv
        ///ptr: qfq xcm zzt
        ///rph: tpj cgh
        ///gkv: xkx fnq fmh vpv
        ///rkp: vfl rrs cjl cbz
        ///rql: mdh plj [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jqt: rhn xhk nvd
        ///rsh: frs pzl lsr
        ///xhk: hfx
        ///cmg: qnr nvd lhk bvb
        ///rhn: xhk bvb hfx
        ///bvb: xhk hfx
        ///pzl: lsr hfx nvd
        ///qnr: nvd
        ///ntq: jqt hfx bvb xhk
        ///nvd: lhk
        ///lsr: lhk
        ///rzs: qnr cmg lsr rsh
        ///frs: qnr lhk lsr.
        /// </summary>
        internal static string InputTest1 {
            get {
                return ResourceManager.GetString("InputTest1", resourceCulture);
            }
        }
    }
}
