//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode23Day15.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode23Day15.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bvm=6,mn-,gt=2,bc=2,nfn=1,cz-,ptq-,mt-,flj=4,dmnj=4,jppb=9,vzzgbv-,ccj=7,jbkdsm-,jfzcm-,zxf-,scjz=5,gqz-,tbs-,qzcb-,jg=7,nvz=7,zf=9,mkj-,nc=7,gsnbj-,bcs-,cgb=5,zljm=7,fsqtxt=3,zbm=5,lnd-,ddf-,qx-,jc-,xh-,kxvc-,fzm-,sxfqnm=1,lnd-,jrxgf=8,zbm-,dp-,lj-,cqp-,bb=4,clf-,msbxx-,vft-,nsstz-,scqj=4,ns-,jjr=1,lqzlm-,zdxd-,cf=6,tbs-,vb=9,nbk-,bdt=3,lhd=8,tzmz=9,rpc=3,rnx-,lhhbz-,vdt=7,kqq=3,np-,cqk=9,hcld-,fsqtxt-,vglgq-,xrn-,xnvv=3,ccj=5,zf-,kc=7,jbkdsm=1,vpl=1,hx=9,mc-,hk-,qk-,nc=1,tsnv=9,dztd=4,bgv-,tt=1,hqh-,ljr=4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rn=1,cm-,qp=3,cm=2,qp-,pc=4,ot=9,ab=5,pc-,pc=6,ot=7.
        /// </summary>
        internal static string InputTest1 {
            get {
                return ResourceManager.GetString("InputTest1", resourceCulture);
            }
        }
    }
}
