//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode23Day18.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode23Day18.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to L 7 (#1dc5f0)
        ///U 6 (#4497e3)
        ///L 3 (#3b21c0)
        ///U 3 (#3d8523)
        ///L 9 (#58e7b2)
        ///U 8 (#35d213)
        ///L 10 (#329390)
        ///D 3 (#1302b3)
        ///R 7 (#07f802)
        ///D 8 (#38fbd3)
        ///L 7 (#6d0e72)
        ///D 6 (#2c2493)
        ///L 5 (#38b7d0)
        ///U 6 (#2ab7b3)
        ///L 2 (#0ce560)
        ///U 6 (#2ab7b1)
        ///L 2 (#2f6940)
        ///U 2 (#2a5a83)
        ///L 3 (#477150)
        ///D 11 (#0baea3)
        ///L 4 (#3899c0)
        ///D 3 (#34a803)
        ///L 5 (#55c0d0)
        ///U 9 (#328483)
        ///L 2 (#460290)
        ///U 5 (#48cfd3)
        ///L 4 (#1e3150)
        ///U 5 (#3b7ea3)
        ///L 7 (#2c0a10)
        ///U 11 (#51d803)
        ///L 4 (#39fe80)
        ///U 3 (#51d801)
        ///R 10 (#2938e0)
        ///U 2 (#1c17f3) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R 6 (#70c710)
        ///D 5 (#0dc571)
        ///L 2 (#5713f0)
        ///D 2 (#d2c081)
        ///R 2 (#59c680)
        ///D 2 (#411b91)
        ///L 5 (#8ceee2)
        ///U 2 (#caa173)
        ///L 1 (#1b58a2)
        ///U 2 (#caa171)
        ///R 2 (#7807d2)
        ///U 3 (#a77fa3)
        ///L 2 (#015232)
        ///U 2 (#7a21e3).
        /// </summary>
        internal static string InputTest1 {
            get {
                return ResourceManager.GetString("InputTest1", resourceCulture);
            }
        }
    }
}
