//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode23Day10.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode23Day10.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F|J-F|.|.F-F-7-7F--|77F.7.77F|-L7-|7|-|-F-L7.7FJF-7-JF7.77-F.7F7.FLF7-FF-L7F--F-J-..J-FJ-FLF7.FF.-F7-|-.F7--77F---7-LF7FFL7.F7|7FJ-FL-.-FJ-F
        ///-L7-FL7--77J|.7.LJFJFLL.F-F-7JLL7-|-|F|L-.L||||7LJ.LF||LJL|L7FF.F|L||.|7-LFFJ.F7L7FJ|.7.F7.||J-F--|J7LLJJL-|-LL.L-7LLJ7-JFLF---FJ|FJ.L77L|J|
        ///LLF-7LJ77|.77FJ-JLL-|-LLJF.JJJ.F7L|7L7.FJ.F-7J|77F|--J7JFFJFLLL|7JF7F--J.||L7.L7FJ-7|-F.L-FJ|LLL-FF77FJL-.-JLLL7.F|.-L-7L7|J7|L|7.J-L-JJ.-FJ
        ///.|F7L-L7J77JLJ.|7|FFL-7|7L7F|JFLJ.LJ|L-LJF|.|J||L|7-L77.F7J7|FLL--||7JF-|-7L-FJJL.L7JF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -L|F7
        ///7S-7|
        ///L|7||
        ///-L-J|
        ///L|-JF.
        /// </summary>
        internal static string InputTest1 {
            get {
                return ResourceManager.GetString("InputTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-F7-
        ///.FJ|7
        ///SJLL7
        ///|F--J
        ///LJ.LJ.
        /// </summary>
        internal static string InputTest2 {
            get {
                return ResourceManager.GetString("InputTest2", resourceCulture);
            }
        }
    }
}
