//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode23Day10.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode23Day10.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F|J-F|.|.F-F-7-7F--|77F.7.77F|-L7-|7|-|-F-L7.7FJF-7-JF7.77-F.7F7.FLF7-FF-L7F--F-J-..J-FJ-FLF7.FF.-F7-|-.F7--77F---7-LF7FFL7.F7|7FJ-FL-.-FJ-F
        ///-L7-FL7--77J|.7.LJFJFLL.F-F-7JLL7-|-|F|L-.L||||7LJ.LF||LJL|L7FF.F|L||.|7-LFFJ.F7L7FJ|.7.F7.||J-F--|J7LLJJL-|-LL.L-7LLJ7-JFLF---FJ|FJ.L77L|J|
        ///LLF-7LJ77|.77FJ-JLL-|-LLJF.JJJ.F7L|7L7.FJ.F-7J|77F|--J7JFFJFLLL|7JF7F--J.||L7.L7FJ-7|-F.L-FJ|LLL-FF77FJL-.-JLLL7.F|.-L-7L7|J7|L|7.J-L-JJ.-FJ
        ///.|F7L-L7J77JLJ.|7|FFL-7|7L7F|JFLJ.LJ|L-LJF|.|J||L|7-L77.F7J7|FLL--||7JF-|-7L-FJJL.L7JF [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -L|F7
        ///7S-7|
        ///L|7||
        ///-L-J|
        ///L|-JF.
        /// </summary>
        internal static string InputTest1 {
            get {
                return ResourceManager.GetString("InputTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7-F7-
        ///.FJ|7
        ///SJLL7
        ///|F--J
        ///LJ.LJ.
        /// </summary>
        internal static string InputTest2 {
            get {
                return ResourceManager.GetString("InputTest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ...........
        ///.S-------7.
        ///.|F-----7|.
        ///.||.....||.
        ///.||.....||.
        ///.|L-7.F-J|.
        ///.|..|.|..|.
        ///.L--J.L--J.
        ///............
        /// </summary>
        internal static string InputTest3 {
            get {
                return ResourceManager.GetString("InputTest3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .F----7F7F7F7F-7....
        ///.|F--7||||||||FJ....
        ///.||.FJ||||||||L7....
        ///FJL7L7LJLJ||LJ.L-7..
        ///L--J.L7...LJS7F-7L7.
        ///....F-J..F7FJ|L7L7L7
        ///....L7.F7||L7|.L7L7|
        ///.....|FJLJ|FJ|F7|.LJ
        ///....FJL-7.||.||||...
        ///....L---J.LJ.LJLJ....
        /// </summary>
        internal static string InputTest4 {
            get {
                return ResourceManager.GetString("InputTest4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF7FSF7F7F7F7F7F---7
        ///L|LJ||||||||||||F--J
        ///FL-7LJLJ||||||LJL-77
        ///F--JF--7||LJLJ7F7FJ-
        ///L---JF-JLJ.||-FJLJJ7
        ///|F|F-JF---7F7-L7L|7|
        ///|FFJF7L7F-JF7|JL---7
        ///7-L-JL7||F7|L7F-7F7|
        ///L.L7LFJ|||||FJL7||LJ
        ///L7JLJL-JLJLJL--JLJ.L.
        /// </summary>
        internal static string InputTest5 {
            get {
                return ResourceManager.GetString("InputTest5", resourceCulture);
            }
        }
    }
}
