//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode23Day22.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode23Day22.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0,0,192~0,2,192
        ///4,3,209~4,3,211
        ///2,8,209~4,8,209
        ///2,0,91~3,0,91
        ///6,0,247~7,0,247
        ///8,5,22~8,8,22
        ///6,6,195~6,8,195
        ///9,2,3~9,2,5
        ///7,8,198~9,8,198
        ///4,8,35~5,8,35
        ///8,2,94~8,2,96
        ///4,5,136~6,5,136
        ///4,4,259~6,4,259
        ///1,2,95~1,4,95
        ///7,6,39~7,6,42
        ///0,6,68~0,8,68
        ///2,4,156~5,4,156
        ///8,3,175~8,6,175
        ///7,0,17~7,2,17
        ///4,8,139~8,8,139
        ///7,3,163~7,5,163
        ///7,3,72~7,5,72
        ///7,3,153~7,5,153
        ///0,8,31~0,9,31
        ///0,6,228~3,6,228
        ///1,7,11~3,7,11
        ///0,3,3~0,3,5
        ///5,4,35~5,7,35
        ///8,7,88~8,9,88
        ///4,0,252~6,0,252
        ///8,0,134~8,3,134
        ///7,6,107~7,7,107
        ///8, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1,0,1~1,2,1
        ///0,0,2~2,0,2
        ///0,2,3~2,2,3
        ///0,0,4~0,2,4
        ///2,0,5~2,2,5
        ///0,1,6~2,1,6
        ///1,1,8~1,1,9.
        /// </summary>
        internal static string InputTest1 {
            get {
                return ResourceManager.GetString("InputTest1", resourceCulture);
            }
        }
    }
}
