//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode23Day19.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode23Day19.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dc{m&lt;2420:R,R}
        ///jb{s&gt;2618:vv,R}
        ///vxv{m&gt;2362:tsk,m&gt;1949:hpf,qdx}
        ///xs{a&gt;2562:R,a&gt;2291:R,s&lt;3703:R,A}
        ///tl{x&lt;1583:hb,nd}
        ///xk{m&lt;3191:R,a&gt;844:R,a&lt;714:A,A}
        ///sxh{m&gt;128:trk,a&lt;521:qvc,zq}
        ///cxv{s&gt;1082:A,s&lt;1006:R,R}
        ///jsm{a&gt;776:A,m&lt;2436:R,A}
        ///sn{a&lt;295:A,x&lt;1774:fpm,fsk}
        ///lld{m&lt;2279:A,R}
        ///ng{a&lt;590:sdl,a&gt;609:snx,R}
        ///sdl{s&lt;1719:A,a&lt;553:A,s&gt;1738:A,A}
        ///hrd{s&gt;3215:A,a&gt;691:A,m&gt;2571:R,R}
        ///jq{s&lt;2384:A,s&lt;2587:zlc,txr}
        ///gp{x&gt;3310:R,s&lt;3337:R,R}
        ///nk{a&lt;3026:jbp,sm}
        ///kth{s&gt;2224:A,R}
        ///plr{x&lt;1171:A,x&gt;1291:A,R}
        ///mzl{m&gt;2788:R,R}
        ///clc{s&gt;2151 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to px{a&lt;2006:qkq,m&gt;2090:A,rfg}
        ///pv{a&gt;1716:R,A}
        ///lnx{m&gt;1548:A,A}
        ///rfg{s&lt;537:gd,x&gt;2440:R,A}
        ///qs{s&gt;3448:A,lnx}
        ///qkq{x&lt;1416:A,crn}
        ///crn{x&gt;2662:A,R}
        ///in{s&lt;1351:px,qqz}
        ///qqz{s&gt;2770:qs,m&lt;1801:hdj,R}
        ///gd{a&gt;3333:R,R}
        ///hdj{m&gt;838:A,pv}
        ///
        ///{x=787,m=2655,a=1222,s=2876}
        ///{x=1679,m=44,a=2067,s=496}
        ///{x=2036,m=264,a=79,s=2244}
        ///{x=2461,m=1339,a=466,s=291}
        ///{x=2127,m=1623,a=2188,s=1013}.
        /// </summary>
        internal static string InputTest1 {
            get {
                return ResourceManager.GetString("InputTest1", resourceCulture);
            }
        }
    }
}
