//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode23Day07.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode23Day07.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 55559 2
        ///Q525J 656
        ///457J4 324
        ///T6668 259
        ///38847 640
        ///777T3 595
        ///J545J 876
        ///25554 748
        ///353T3 974
        ///6KQKK 178
        ///A3353 31
        ///23239 195
        ///J3TTT 238
        ///897A3 580
        ///QAKJ3 701
        ///J6758 273
        ///666J8 475
        ///A4K5K 241
        ///9T4TJ 32
        ///K9K4J 786
        ///69666 472
        ///AJKAT 389
        ///8Q73J 204
        ///9K8KK 780
        ///886J4 855
        ///8T8TJ 828
        ///5TQA2 64
        ///3Q6Q6 638
        ///TTJTT 601
        ///K2J5K 338
        ///QQQTQ 196
        ///Q8JQ8 801
        ///7AK3J 437
        ///Q8535 1000
        ///K2JK3 853
        ///A3J86 672
        ///TJT9J 107
        ///89Q9K 127
        ///A794K 242
        ///J8A22 819
        ///66688 690
        ///35357 861
        ///JK87J 864
        ///46KJ7 642
        ///829J5 890
        ///22JJJ 334
        ///4J959 795        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Input1 {
            get {
                return ResourceManager.GetString("Input1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 32T3K 765
        ///T55J5 684
        ///KK677 28
        ///KTJJT 220
        ///QQQJA 483.
        /// </summary>
        internal static string InputTest {
            get {
                return ResourceManager.GetString("InputTest", resourceCulture);
            }
        }
    }
}
